- name: âœ¨ feature
  color: 5319E7
  description: "A new feature"
- name: ğŸ› bug
  color: D73A4A
  description: "A bug fix"
- name: ğŸ“ documentation
  color: 0075CA
  description: "Documentation only changes"
- name: ğŸ¨ style
  color: CFD3D7
  description: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
- name: â™»ï¸ refactor
  color: 03BC5E
  description: "A code change that neither fixes a bug nor adds a feature"
- name: ğŸ§ª test
  color: A2EEEF
  description: "Adding missing tests or correcting existing tests"
- name: ğŸ”§ chore
  color: 5fBCA04
  description: "Changes to the build process or auxiliary tools and libraries such as documentation generation"
- name: ğŸ”– release
  color: E99695
  description: "Create a release commit"
- name: â“ question
  color: CC317C
  description: "Further information is requested"
- name: ğŸ‘· ci/cd
  color: 64B5F6
  description: "Changes to our CI/CD configuration files and scripts"
- name: ğŸ—ï¸ build
  color: 7057FF
  description: "Changes that affect the build system or external dependencies (example scopes: gradle, npm, make, etc)"
