filters:
  - label: âœ¨ feature
    regexs:
      - /\[(feat|feature)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ› bug
    regexs:
      - /\[(fix|bug)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ“ documentation
    regexs:
      - /\[(docs|doc|documentation)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ¨ style
    regexs:
      - /\[(style|styling)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: â™»ï¸ refactor
    regexs:
      - /\[(refactor|refactoring)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ§ª test
    regexs:
      - /\[(test|testing)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ”§ chore
    regexs:
      - /\[(chore|etc)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ”– release
    regexs:
      - /\[(release)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: â“ question
    regexs:
      - /\[(question)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ‘· ci/cd
    regexs:
      - /\[(ci/cd|ci|cd)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ğŸ—ï¸ build
    regexs:
      - /\[(build)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
