server:
  port: ${APPLICATION_PORT:9000}

spring:
  application:
    name: namo

  profiles:
    group:
      local:
        - local
        - auth
        - db
        - docs
        - aws
      dev:
        - dev
        - auth
        - db
        - docs
        - aws
      prod:
        - prod
        - auth
        - db
        - aws
